baseURL = "https://lyrning.github.io/lyrning_website/"
languageCode = "es-es"
title = "Lyrning"
theme = "ananke"
publishDir = "docs"

[menu]

  [[menu.main]]
    name = "pricing"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/pricing/"
    weight = -120

  [[menu.main]]
    identifier = "english lesson trial!"
    name = "english lesson trial"
    pre = "<i class='fa fa-heart'></i>"
    url = "/english-lesson-trial/"
    weight = -110

  [[menu.main]]
    identifier = "about"
    name = "about"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -100  